### ISSUE TITLE
[SMB261/263] flir spinnaker SDK missing

### ISSUE THREAD

**Issue by hermannsblum** [ETHZ-RobotX/smb_dev#12]
The robot with the SMB263 tracking camera and the SMB261 wifi and base does not have the flir spinnaker sdk installed.

**Comment by hermannsblum** [comment]
I wanted to test camera drivers on the new system, but had to leave before getting it to work. 

Network however works as good as I never experienced, nice job!

**Comment by mantelt** [comment]
yes, sorry, I forgot to mention that there is no software besides the OS installed at the moment.

I did some tests on my own to have the versavis + FLIR Blackfly running on Ubuntu Focal / ROS Noetic. For me, it works with the following setup:
- Versavis: use [test/upstream_rosserial](https://github.com/ethz-asl/versavis/tree/test/upstream_rosserial) branch (make sure to update submodule rosserial)
- Spinnaker driver: I installed on my system the spinnaker driver v 2.2.0.48 from https://meta.box.lenovo.com/v/link/view/a1995795ffba47dbbe45771477319cc3 (spinnaker -> archive -> 2.2.0.48)
- flir_camera_driver / spinnaker_camera_driver :  https://github.com/ethz-asl/flir_camera_driver branch fix/newspinnaker (which apparently is merged into master now and deleted).

**Comment by hermannsblum** [comment]
Yes, that setup sounds about right. Did you experience problems with Qt? Were you able to launch rviz after installing spinnaker 2.2? That was an issue I so far could not resolve on my machine.

**Comment by mantelt** [comment]
ahh... I only installed the drivers, not spinview and stuff. 
check also the [readme](https://github.com/ethz-asl/flir_camera_driver/blob/master/README.md) in https://github.com/ethz-asl/flir_camera_driver

**Comment by mantelt** [comment]
> yes, sorry, I forgot to mention that there is no software besides the OS installed at the moment.
> 
> I did some tests on my own to have the versavis + FLIR Blackfly running on Ubuntu Focal / ROS Noetic. For me, it works with the following setup:
> 
>     * Versavis: use [test/upstream_rosserial](https://github.com/ethz-asl/versavis/tree/test/upstream_rosserial) branch (make sure to update submodule rosserial)
> 
>     * Spinnaker driver: I installed on my system the spinnaker driver v 2.2.0.48 from https://meta.box.lenovo.com/v/link/view/a1995795ffba47dbbe45771477319cc3 (spinnaker -> archive -> 2.2.0.48)
> 
>     * flir_camera_driver / spinnaker_camera_driver :  https://github.com/ethz-asl/flir_camera_driver branch fix/newspinnaker (which apparently is merged into master now and deleted).

_UPDATE_
* Versavis: use [test/upstream_rosserial](https://github.com/ethz-asl/versavis/tree/test/upstream_rosserial) branch (make sure to update submodule rosserial)
* Spinnaker driver: I installed on my system the spinnaker driver v 2.4.0.143 from https://flir.app.boxcn.net/v/SpinnakerSDK/folder/133154514756 
* flir_camera_driver / spinnaker_camera_driver :  https://github.com/ethz-asl/flir_camera_driver , `master` branch

**Comment by hermannsblum** [comment]
Update: Had to change the `flir_camera_driver` to master, now everything works both with onboard cam and my cameras on SMB261. (Fixed in #5c4ffc1)
